version: '3'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=vic_emissions
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=password1234
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./onboarding-backend/
    image: jirathipk/vic-emissions-backend:latest
    ports:
      - "7999:8000" # <local-host>:<container-port>
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_NAME=vic_emissions
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password1234
      - DATABASE_USERNAME=db_user
    depends_on:
      - db

  frontend:
    build: 
      context: ./onboarding-frontend/
      args: 
        - REACT_APP_API_URL=http://localhost:7999/api/
    
    image: jirathipk/vic-emissions-frontend:latest
    ports:
      - "8081:80" # <local-host>:<container-port>
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres_data: